#' @importFrom httr GET
#' @importFrom httr content
#' @importFrom httr modify_url
#' @importFrom httr status_code
#' @importFrom rvest html_text
#' @importFrom tibble tibble
#' @importFrom glue glue
#' @importFrom stringr str_extract_all
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_subset
#' @importFrom stringr regex
#' @importFrom utils tail
#' @importFrom cli cli_progress_along
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_alert_info
#' @importFrom dplyr mutate
#' @importFrom dplyr rename
#' @importFrom dplyr relocate
#' @importFrom dplyr select
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr slice_sample
#' @importFrom dplyr group_map
#' @importFrom dplyr pull
NULL